/* 
 * 7. Prime numbers and also be generated by an algorithm know as the 
 *    Sieve of Eratosthenes. The algorithm for this procedure is presented here.
 *    Write a program that impolements this algorithm. Have the program find all
 *    prime numbers up to n = 150. What can you say about this algorithm as 
 *    compared to the ones used in the text for calculating prime numbers?
 *    
 *    Sieve of Eratosthenes Algorithm
 *    
 *    To Display All Prime Numbers Between 1 and n
 *      Step 1: Define an array of integers P. 
 *              Set all elements Pi to 0,2 <= i <= n.
 *      Step 2: Set i to 2.
 *      Step 3: If i > n, the algorithem terminates.
 *      Step 4: If Pi is 0, then i is prime.
 *      Step 5: For all positive integer values of j, 
 *              such that i x j <= n, set Pixj to 1.
 *      Step 6: Add 1 to i and go to step 3.
 */

#include <stdio.h>

int main(void)
{
  int i, j, n;
  
  printf("Input: n = ");
  scanf("%i", &n);
  
  // define an array of integer P
  int P[n + 1];
  
  // set array P value all 0
  for (i = 1; i <= n; ++i)
    P[i] = 0;
  
  // prime number testing 
  for (i = 2; i <= n; ++i)
    for (j = i; i * j <= n; ++j)
      P[i * j] = 1;
  
  // print all prime numbers
  for (i = 2; i < n; ++i)
    if (P[i] == 0)
      printf("%i ", i);
  
  printf("\n");

  return 0;
}
